- examples/apps/screenpipe-app-tauri/src-tauri/src/main.rs
> Add system tray icon macos

- screenpipe-audio/src/core.rs
[Issue 127](https://github.com/louis030195/screen-pipe/issues/127)
- When default_input_config() was called on a output device, the tread paniced.
How to previously product the bug:
```
build the project
screenpipe --list-audio-devices
screenpipe --audio-device "myaudio device"
```
After the changes, made a build and tested the above, it run properly without the panic and error. Also, the correct audio is being stored properly of 30 seconds. Tried recording a few things and it was working.
Also, I think we there is no need to make the config `mutable` anymore. [Let me know if there is something which could break due to this]
/claim #127
> audio output fails when default_input_config() on output device [Windows]

- screenpipe-server/Cargo.toml
Fix windows build:
```
Compiling sqlx-macros v0.7.4
Compiling console-api v0.7.0
Compiling ffmpeg-next v7.0.4
Compiling screenpipe-vision v0.1.68 (D:\Projects\screen-pipe\screenpipe-vision)
error: failed to run custom build command for `v8 v0.92.0`
```
> fix windows build

- examples/apps/screenpipe-app-tauri/components/chat-list-openai-v2.tsx
Hey! I managed to build screenpipe earlier and have been playing with it on and off, cool project!
I noticed some fairly consistent issues with relative queries pretty quickly, which I narrowed down to a couple of issues:
- Inspecting the tool calls, the AI (gpt-4o) was fluctuating between the UTC time and local time randomly
- The tool call was using a date equivalent to 9th January (I'm in the UK)!
Both of these combined led to some very inconsistent tool calls, which meant in my testing a query like "what apps have I used in the last 20 minutes?" with data present would return nothing, as _one_ of the components would always be wrong.
To address this, I've fairly significantly altered the prompts to use `toString` (which is stable in output format per-implementation) instead of …
> Enhance app datetime handling across timezones

- Cargo.toml
- examples/apps/screenpipe-app-tauri/src-tauri/Cargo.toml
- screenpipe-audio/benches/record_and_transcribe_benchmark.rs
- screenpipe-server/src/bin/screenpipe-server.rs
- screenpipe-server/src/core.rs
- screenpipe-server/src/video.rs
- screenpipe-vision/src/core.rs
- screenpipe-vision/src/microsoft.rs
- separate audio and vision jobs into their own runners
- specify 4 threads for tokio runner
- prevent windows ocr panicking from killing the runner
- bump minor versions
/claim #226
> fix: windows audio vision continuous recording

- screenpipe-audio/src/core.rs
The `default_input_device()` function on core.rs returns a Result<AudioDevice>, but panics if there is none. By replacing the unwrap with ok_or, we prevent panicking and instead return an Error.
> Dont panic if host has no default input device

- .cargo/config.toml
A workaround for #324
There are multiple definitions of a function with the same name in the v8 and ort C bindings. Adding these rustflags lets the linker ignore these errors and pick the first definition it encounters.
> fix: broken linux app builds

- content/docs/NOTES.md
- examples/typescript/apple-shortcut/main.js
- examples/typescript/pipe-meeting-summary-by-email/pipe.ts
- examples/typescript/vercel-ai-chatbot/components/empty-screen.tsx
- screenpipe-app-tauri/components/chat-list-web-llm.tsx
- screenpipe-app-tauri/components/notification-handler.tsx
- screenpipe-app-tauri/src-tauri/gen/schemas/desktop-schema.json
- screenpipe-app-tauri/src-tauri/gen/schemas/macOS-schema.json
- screenpipe-audio/src/core.rs
- screenpipe-server/src/cli.rs
- screenpipe-vision/src/monitor.rs
This pull request includes several typo corrections across multiple files to improve code readability and accuracy. The changes span various components, including documentation, TypeScript code, JSON schemas, and Rust source files.
* [`content/docs/NOTES.md`](diffhunk://#diff-1f9d4d4da656cd5d792e933ffd5dfcb8f593ab72797aeef6cb48f92916e0f515L68-R68): Corrected "sould" to "should".
* [`examples/typescript/apple-shortcut/main.js`](diffhunk://#diff-950bf2bbceb90df11ac31c60081fd1f9022080ec8e5da34b867c2d709156851cL62-R62): Corrected "asnwer" to "answer".
* [`examples/typescript/pipe-meeting-summary-by-email/pipe.ts`](diffhunk://#diff-385d15302a08bae9816efd13913ecfac2cd8f16307a1c16bf016e66d544b025bL7-R7): Corrected "intructions" to "instructions".
* …
> Fix assorted typos and spelling

- content/docs/pages/docs/getting-started.mdx
- I was unable to see the desktop app when installing with `brew`.
- Advanced build steps from source did not mention building of the desktop app either.
- Add step in getting started docs for building OSS desktop app
- Add required `cmake` and `wget` dependencies
- My computer was relatively fresh install of MacOS (I usually develop within Devcontainers) so this will reduce issues for others getting started
> Add step in getting started for building OSS desktop app

- Cargo.toml
This PR fixes hugging face being blocked in China.
User can specify env variable `HF_ENDPOINT=https://hf-mirror.com` for CLI to use China mirror
/claim #341
/closes #341
> fix: screenpipe support in china

- screenpipe-audio/src/core.rs
- screenpipe-core/src/ffmpeg.rs
- screenpipe-server/src/resource_monitor.rs
- screenpipe-vision/build.rs
This is a pretty small pull request but I think it has its merit, this removes all the warnings that Cargo brings up when building the project.
> Remove all the warnings from the code

- content/docs/pages/docs/getting-started.mdx
---
title: "[pr] "
labels: ''
assignees: ''
---
> Neglecting to install cmake leads to error: `failed to run custom build command for 'alsa-sys v0.3.1'` when running cargo build --release on linux (sidenote: I'm using WSL2 running Ubuntu 22.04).
1. [reorder apt-get install command for enhanced readability](https://github.com/mediar-ai/screenpipe/commit/f9cc1af61ec6a7b0a0f18468b3a87bd5888d1e55)
2. [docs: add missing 'cmake' installation step to apt-get instructions for linux](https://github.com/mediar-ai/screenpipe/commit/823665aa4683ce3bf4b5fd148127a95f3dac7e9a)
related issue: none
docs update, no tests to run
none
> documentation: include CMake installation in Linux dependencies

- examples/typescript/pipe-email-exa-search/README.md
- examples/typescript/pipe-email-exa-search/deno.json
- examples/typescript/pipe-email-exa-search/pipe.json
- examples/typescript/pipe-email-exa-search/pipe.ts
---
name: email exa search
about: 
Implements the email exa search pipe which emails a user content relevant to what they have looked on their screen the previous day using Exa.ai.
Related issue: https://github.com/mediar-ai/screenpipe/issues/365
Fixes: https://github.com/mediar-ai/screenpipe/issues/365
/claim https://github.com/mediar-ai/screenpipe/issues/365
---
1. Run the email exa search pipe
> Implement email exa search

- screenpipe-app-tauri/scripts/pre_build.js
---
title: "[pr] fix: build: ignore ~/.wgetrc to avoid interference"
labels: ''
assignees: 'louis030195'
---
Users can define personal settings for wget in `~/.wgetrc`. When the `wget` command is run it reads this configuration file by default and add the corresponding options. The `scripts/pre_build.js` script fails when some user options are specified in the configuration file because they conflict with the options that this script uses. The solution is to ignore this user configuration file.
related issue: ø
1. Create a file `~/.wgetrc` and just put `timestamping = on` inside.
2. Run `bun scripts/pre_build.js` from `screenpipe-app-tauri` and confirm that wget errors out because `-nc` and `--timestamp` can't be combined.
3. Move to …
> fix: build: ignore ~/.wgetrc to avoid interference

- screenpipe-audio/src/audio_processing.rs
- screenpipe-audio/src/core.rs
- screenpipe-audio/src/stt.rs
I identified an issue with the collection of audio data. devices with 2 channels use an interleaved format of [left,right,left,right] and this wasn't accounted for. By converging the left and right audio samples, the transcripts are working again.
related issue: #521
related issue: #525
1. on mac use display audio as an input
2. test transcription
> fix: converge interleaved audio samples

- content/docs/pages/docs/getting-started.mdx
---
title: "[pr] "
labels: ''
assignees: ''
---
Introduced option to skip pre_build script and manually copy files in docs, for the MacBook where script may fail.
Successfully build with M1, M2 and M3 Macbook Pro. 
related issue: https://github.com/mediar-ai/screenpipe/issues/460, https://github.com/mediar-ai/screenpipe/issues/382
1. 
2. 
3. 
> docs: add mac manual prebuild

- screenpipe-app-tauri/components/settings.tsx
- screenpipe-app-tauri/scripts/pre_build.js
- screenpipe-app-tauri/src-tauri/tauri.linux.conf.json
- screenpipe-app-tauri/src-tauri/tauri.windows.conf.json
/claim #507
This correctly copies the ollama bin in Linux and adds the libs as resources.
> Restore ollama Windows and Linux support

- content/docs/theme.config.tsx
The `edit this page` button in the docs points to a non-existing page 
1. Go to the [docs page](https://docs.screenpi.pe/docs/getting-started)
2. click on `Edit this page`
> Fix the `edit this page` button in docs

- screenpipe-app-tauri/components/meeting-history.tsx
Allows users to select the audio devices for a meeting.
Does not affect summary or person identification.
related issue: #553
1. check / uncheck devices
2. verify transcript change
3. 
/claim 553
> add audio device selection to meetings

- screenpipe-app-tauri/scripts/pre_build.js
I think we should use `VCPKG_ROOT` environment variable for vcpkg path in windows build script, since the windows installation guide set this env:
`SET VCPKG_ROOT=V:\packages\vcpkg`
> Use VCPKG_ROOT environment variable for vcpkg path in windows build script

- screenpipe-js/deno.json
- screenpipe-js/main.ts
- screenpipe-js/tests/scheduler.test.ts
- **fix: install missing dependency**
- **ci: use install dependencies bash script**
- **refactor: avoid check for (possibly empty) pipe_id at hoisting stage**
- **docs: remove unnecessary comment**
- **refactor: use `node-cron` and drop cron runtime**
- **test: adapt test scheduler to use `node-cron`**
- **chore: remove unnecessary lib**
> refactor: replace internal runtime with `node-cron` to manage scheduled jobs

- CONTRIBUTING.md
---
title: "Fix rust style guide permalink "
labels: ''
assignees: 'TanGentleman'
---
Old link: https://github.com/rust-lang/style-team/blob/master/guide/guide.md
New link: https://github.com/rust-lang/rust/tree/4f2f477fded0a47b21ed3f6aeddeafa5db8bf518/src/doc/style-guide/src
1. 
2. 
3. 
> Fix CONTRIBUTING.md dead hyperlink

- screenpipe-vision/src/capture_screenshot_by_window.rs
---
title: "optimize window validation logic"
labels: 'enhancement'
assignees: 'TanGentleman'
---
Improve performance of is_valid_window() with several optimizations:
- Add early returns for simple checks to avoid unnecessary processing
- Cache lowercase string conversions of window name/title to prevent repeated allocations 
- Restructure logic flow to exit early on ignore list matches
- Skip include list processing when empty
No changes in behavior, purely performance improvements by reducing redundant operations and string allocations.
1. 
2. 
3. 
- [X?] i have added the custom cursor AI prompt to my settings as mentioned in CONTRIBUTING.md and used to write this PR
> optimize window validation logic

- content/docs/styles/globals.css
---
name: correct logo text and GitHub icon colors in light mode
title: "[pr] "
labels: ''
assignees: ''
---
This fixes the issue where the logo text and GitHub icon appeared white in light mode.
1. 
2. 
3. 
> fix: correct logo text and GitHub icon colors in light mode

- screenpipe-audio/src/audio_processing.rs
---
title: "[pr] "
labels: ''
assignees: ''
---
Silero treats NaN as speech. Display output silence becomes NaN because of division by zero in the normalize function.
1. turn on screenpipe with output and no audio playing.
> fix Silero Silence Speech detection

- .github/workflows/ci.yml
- .github/workflows/release-app.yml
@louis030195 So we can do the release, at least for now - once the server is ready we will switch the release app back to Windows.
> Switch to windows-latest temporarily

- screenpipe-app-tauri/scripts/pre_build.js
@louis030195 Fixes the mirrors used to download the ffmpeg binaries - these are listed in the official ffmpeg page so i'd say they're good to use.
Mostly so we don't get blocked by SourceForge.
> Use better mirror for ffmpeg downloads

- screenpipe-app-tauri/app/page.tsx
- screenpipe-app-tauri/components/context-usage-indicator.tsx
- screenpipe-app-tauri/components/search-chat.tsx
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> headline, preview of search results, hide selection, deduplication button, quick filters

- screenpipe-app-tauri/package.json
- Update @radix-ui/react-popover to ^1.1.2 that eventually fix the focusing issue of the combobox items.
related issue: #679 #654 
1. Make sure to have `"@radix-ui/react-popover": "^1.1.2"` under `dependencies` in /screenpipe-app-tauri/package.json
2. Run `bun install` from /screenpipe-app-tauri in your terminal to update @radix-ui/react-popover
3. Run `bun tauri dev`
4. Once the application has started, go to Settings menu and check the following combobox elements are properly working
- monitors
- audio devices
- languages
https://github.com/user-attachments/assets/3da3f06f-2993-4029-8b76-1a62527ebed3
I tried inspecting related components from shadcn library but they all looked good and don't seem …
> fix: can focus combobox items (#679)

- content/docs/pages/docs/getting-started.mdx
---
name: chore: release screenpipe to official Homebrew/core
about: updates the docs to use official homebrew instead of repository tap
title: "chore: release screenpipe to official Homebrew/core"
labels: ''
assignees: ''
---
release screenpipe to official Homebrew/core
Closes #614 
/claim #614 
related PR on homebrew https://github.com/Homebrew/homebrew-core/pull/196345
> chore: release screenpipe to official Homebrew/core

- examples/typescript/pipe-obsidian-time-logs/README.md
- examples/typescript/pipe-obsidian-time-logs/pipe.json
- examples/typescript/pipe-obsidian-time-logs/pipe.ts
---
name: pipe-obsidian-time-logs
about: add time logging to obsidian
title: "[pr] "
labels: ''
assignees: ''
---
/claim #676
This PR adds a new pipe which logs engineering work to your obsidian vault. Screen data is processed by either openai or ollama model.
related issue: #676 
1. Add this pipe to your pipes
2. Set obsidian path
3. Set openai or ollama in pipe's settings
> add time logs to obsidian pipe

- .cargo/config.toml
- Cargo.toml
- screenpipe-app-tauri/src-tauri/Cargo.lock
- screenpipe-vision/build.rs
fresh git clone and build 
```cargo build --release --features metal```
resulted in:
screenpipe/target/release/deps/screenpipe_vision-f8108412ff8ef1ec" "-Wl,-dead_strip" "-nodefaultlibs"
= note: ld: library 'screenpipe' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: could not compile `screenpipe-vision` (bin "screenpipe-vision") due to 1 previous error
> fix: build for macos

- screenpipe-server/src/core.rs
---
title: "[pr] "
labels: ''
assignees: ''
---
Transcript was sometimes set to empty. This PR makes sure that the transcript is not updated if it is empty, and also makes sure that it is not updated if it is the same text after processing the overlap.
related issue: #701
1. use screenpipe and talk into the microphone for a few cycles.
2. check that the transcript is not empty in the db.
> Fix overlap #701

- .github/workflows/release-cli.yml
---
name: feat: automate brew formula update
about: automate brew formula update
title: "feat: automate brew formula update"
labels: ''
assignees: ''
---
automate brew formula update using `brew bump-formula-pr`
Closes #692
/claim #692 
> feat: automate brew formula update

- screenpipe-audio/build.rs
@louis030195 Might be needed since GitHub Actions uses UTF-8 encoding for downloads.
> Copy zipfile as bytes

- screenpipe-app-tauri/components/timeline/timeline-dock-section.tsx
- screenpipe-app-tauri/src-tauri/Cargo.toml
- screenpipe-app-tauri/src-tauri/src/icons.rs
---
name: timeline apps icon for linux
about: this will add app icons in timeline ui on linux, i used a [`gtk`](https://crates.io/crates/gtk) crate for getting the icon path and info, but the icon was in svg format, so i need to do some changes in `timeline-dock-section.tsx`  bcz converting svg icon to png will require some extra crate. also in linux timeline isn't streaming frames so its hard to attach screenshots, but i've tested [this](https://github.com/tribhuwan-kumar/screenpipe/blob/3a2bf72f658055dfacc7762479853c5a5a1e7c17/screenpipe-app-tauri/src-tauri/src/icons.rs#L266) function outside the app & i'm sure it will work! 
title: "[pr] "
labels: ''
assignees: ''
fix: #712
/claim #712
---
related issue: #712 
add a few steps to test the pr …
> feat: add timeline icon in linux

- content/docs/pages/docs/getting-started.mdx
This PR adds two system packages required to build screenpipe on a Ubuntu system, specifically on a container created from the `ubuntu-toolbox:24.04` image.
Missing `libssl-dev` resulted in `error: failed to run custom build command for 'openssl-sys v0.9.104'`.
Missing C++ compiler resulted in error when compiling `esaxx-rs`.
Run a `ubuntu-toolbox:24.04` container, and build screenpipe successfully using provided instructions.
> add missing dependencies in Linux build instructions

- .github/workflows/release-app.yml
/claim #321 
/closes #321
@louis030195 You need to define the GitHub Actions secret "SIGNPATH_API_TOKEN" with a token you can get with the guide at https://about.signpath.io/documentation/users#interactive-api-token
Simply enter your profile, and click in generate token.
Also, let me know when you get a release certificate from Signpath, to change it to release-signing.
> Sign Windows binaries with test key

- .github/workflows/release-app.yml
@louis030195 Should fix the issue, our self-hosted runners don't have python.
> Install Python for MKL setup

- screenpipe-app-tauri/components/timeline/timeline-dock-section.tsx
- screenpipe-app-tauri/src-tauri/Cargo.toml
- screenpipe-app-tauri/src-tauri/src/icons.rs
---
fix: #798 
about: this will fix the creating infinite powershell window on invocation of `get_app_icon` and limit the powershell process which was abusing system resources. also used `localforage` for icon caching (including in memory cache). so it won't need to invoke command every time to get base64 of icon. 
the concurrency process limit is 5, assuming every screenpipe user have 16GB of ram!
i should've done in this https://github.com/mediar-ai/screenpipe/pull/706, sorry for the inconvenience!
title: "[pr] "
labels: ''
assignees: ''
---
related issue: #798
1. 
2. 
3. 
any other …
> fix: infinite loop of creating powershell windows

- screenpipe-audio/build.rs
/claim #794 
/closes #794 
@louis030195 Fixes the issue by copying the newer library so Windows doesn't use the included one in system32.
> Make sure ONNX is copied into output folder

- screenpipe-server/src/migrations/20241210111055_add_fts_update_delete_triggers.sql
1. FTS triggers for UPDATE and DELETE were absent.
2. Only INSERT triggers were defined :
- Updated records in the main tables were not reflected in the FTS tables
- Deleted records in the main tables remained in the FTS tables
1. Triggers for UPDATE and DELETE on the following tables:
- ocr_text
- audio_transcriptions
- ui_monitoring
fixes #904 
/claim #904
> Add UPDATE and DELETE triggers for FTS tables

- install.sh
Adds install.sh script to handle dynamic library linking and security attributes on macOS (using rpaths and quarantine removal)
https://github.com/user-attachments/assets/841ba5f3-28db-4f5b-b90f-995932ed54c4
```bash
sudo ./install.sh
```
/closes https://github.com/mediar-ai/screenpipe/issues/915
/claim https://github.com/mediar-ai/screenpipe/issues/915
> (feat) macOS/Linux one-liner installation script 

- screenpipe-app-tauri/components/auth.tsx
- screenpipe-app-tauri/components/stripe-subscription-button.tsx
---
title: "[pr] Fix app build errors related to User object inconsistencies"
labels: 'bug'
assignees: ''
---
PR fixes build issues created by code that expects the `user_id` property and `checkLoomSubscription` members on the `User` interface/object that do not (yet?) exist and are probably coming in another PR, but made it in here too early perhaps by accident and are preventing the build from succeeding. 
try to build app, it should build. 
fixes https://github.com/mediar-ai/screenpipe/issues/941
> Fix app build errors related to User object inconsistencies

- screenpipe-app-tauri/components/video.tsx
/claim #666
https://github.com/user-attachments/assets/f0c2d821-cf3c-4c32-9ac8-5c6be0b7de28
> feat: include `hvc1` codec to load h.265 videos

- screenpipe-audio/src/stt.rs
- screenpipe-audio/tests/accuracy_test.rs
Fixes transcription accuracy test.
`cargo test <features> --package screenpipe-audio --test accuracy_test -- test_transcription_accuracy --exact --show-output --ignored --nocapture`
> fix accuracy_test

- screenpipe-app-tauri/src-tauri/src/updates.rs
---
title: "[pr] "
labels: ''
assignees: ''
---
when we run `bun tauri dev` or `bun tauri build --debug` then the value of Environment variable
TAURI_ENV_DEBUG = true 
in all other commands it is false
Reference: https://v2.tauri.app/reference/environment-variables/#tauri-cli-hook-commands
closes #539 
1. do `bun tauri dev`
2. see that it doesn't check for updates
> feat: disable update check in bun tauri dev

- install.sh
---
name: Cross-platform Version Parsing Update
about: Updates version parsing logic in install script
title: "[PR] Improve version extraction for cross-platform compatibility"
labels: 'enhancement'
assignees: ''
---
Updates the version extraction logic in the install script to use a more robust and cross-platform compatible approach using grep and sed. This change improves reliability when parsing GitHub release versions across different platforms and shell environments.
The new implementation:
- Uses a more reliable grep pattern that handles varying whitespace
- Simplifies the parsing chain to reduce potential points of failure
- Maintains compatibility across different Unix-like systems
Related issue: N/A
1. Run the install script on different platforms (macOS, Linux) to verify version …
> Improves version extraction in installation script

- screenpipe-app-tauri/src-tauri/Cargo.lock
- screenpipe-core/src/pipes.rs
This PR runs the Next.js pipes in production mode.
Cases
Requisite PR that needs to be merged first https://github.com/mediar-ai/screenpipe/pull/1079 it involves all the heavy work involved to make this one work.
/claim #970
/closes #970
> run next.js pipes in production mode

- content/docs/pages/docs/getting-started.mdx
The PowerShell script wasn't working on Windows, it was just a copy of the script for Unix.
As it turns out, Windows has a cmdlet (a PowerShell command) called curl that takes precedence over the actual curl binary, so we have to temporarily remove that alias in order to run this command (and of course, the user also has to have curl, jq, and sed installed as with the other scripts).
As you can see in the image, `Remove-item alias:curl;` will fail if the user has already removed it, but the command will continue so it's fine.
Before:
After:
> Fix powershell script in getting-started.mdx

- screenpipe-audio/src/bin/screenpipe-audio-forever.rs
- screenpipe-audio/src/bin/screenpipe-audio.rs
- screenpipe-audio/src/core.rs
- screenpipe-audio/src/deepgram/realtime.rs
- screenpipe-audio/src/lib.rs
- screenpipe-audio/src/stt.rs
- screenpipe-audio/src/whisper/model.rs
- screenpipe-core/src/devices.rs
- screenpipe-core/src/lib.rs
- screenpipe-server/src/bin/screenpipe-server.rs
- screenpipe-server/src/core.rs
- screenpipe-server/src/db.rs
- screenpipe-server/src/db_types.rs
- screenpipe-server/src/server.rs
- screenpipe-server/src/video.rs
- screenpipe-vision/src/bin/screenpipe-vision.rs
- screenpipe-vision/src/core.rs
- screenpipe-vision/src/monitor.rs
This PR adds endpoints to control vision devices individually. Here's how to test:
```bash
cargo build --release [ --features metal ]
```
open https://www.youtube.com/watch?v=4HRWgnHDu-w in another tab
```bash
./target/release/screenpipe --data-dir /tmp/sp --port 3035 --disable-vision --debug
```
First, list available audio devices and store the first one:
```bash
curl http://localhost:3035/audio/list | jq
AUDIO_DEVICE=$(curl http://localhost:3035/audio/list | jq -r '.[0].name')
curl -X POST http://localhost:3035/audio/stop \
-H "Content-Type: application/json" \
-d "{\"device_name\": \"$AUDIO_DEVICE\"}"
curl -X POST http://localhost:3035/audio/start \
-H "Content-Type: application/json" \
-d "{\"device_name\": \"$AUDIO_DEVICE\"}"
```
```bash
./target/release/screenpipe --fps 1 --data-dir …
```
> [looking for testers urgently] start and stop vision device on demand through /vision/start

- screenpipe-app-tauri/components/recording-settings.tsx
improves a bit but there's still work to be done for #1223 
here is what the new thing looks like
also, if the user tries to remove all the monitors, the option "disable video recording" will be turned on automatically.
> feat: improve multi-monitor experience

- .github/workflows/release-app.yml
- install.ps1
@louis030195 Fixes build
https://vcredist.com/quick/
Uses their suggested script
> Use VcRedist module install script to fix CI

- screenpipe-js/browser-sdk/src/index.ts
- screenpipe-js/node-sdk/src/PipesManager.ts
- screenpipe-js/node-sdk/src/index.ts
---
name: Add pipe management to Node SDK
about: Add pipes functions
title: "Add pipe management to Node SDK"
labels: ''
assignees: ''
---
Adds the following functions to the Node SDK:
- pipe.pipes.list()
- pipe.pipes.download()
- pipe.pipes.enable()
- pipe.pipes.disable()
- pipe.pipes.update()
related issue: #1283
1. Run screenpipe server at localhost:3030
2. Instantiate NodePipe class
3. Run all functions in `.pipes`
/claim #1283
> Add pipe management to Node SDK

- screenpipe-actions/ai-proxy/src/providers/anthropic.ts
- screenpipe-actions/ai-proxy/src/providers/gemini.ts
- screenpipe-actions/ai-proxy/src/providers/openai.ts
- screenpipe-actions/ai-proxy/src/types.ts
Added json schema response format for openai, claude and gemini
related issue: #1299 
/claim #1299
openai
claude
gemini
> feat: added response format

- screenpipe-app-tauri/components/login-dialog.tsx
- screenpipe-app-tauri/components/pipe-store.tsx
- screenpipe-app-tauri/src-tauri/src/updates.rs
The app will now emit an "update-all-pipes" event to the front-end when running `check_for_updates` (which happens Rust-side every 5 minutes).
When the front-end catches this event, the pipe-store component will run `handleUpdateAllPipes`, but it won't show the login dialog or the toast unless updates are found.
I'm not able to test if it runs properly when there is an update because that requires access to `https://screenpi.pe/api/plugins`, but I can confirm it works when `pipesToUpdate` is set manually.
/claim #1292
/closes #1292
> Make pipes update in background

- screenpipe-app-tauri/lib/hooks/use-health-check.tsx
- screenpipe-server/src/server.rs
this is from backend `ws://127.0.0.1:3030/ws/health`. 
we've to still depend on interval cause in a case where backend goes down so the health websocket will goes down too (isn't is obvious?) so in this case if we don't use interval user will have to refresh the page to reconnect the websocket.
https://github.com/tribhuwan-kumar/screenpipe/blob/d83e9e9a5699200294979e6241b3f50bbcdabd12/screenpipe-app-tauri/lib/hooks/use-health-check.tsx#L162
also i didn't implement from in `screenpipe-events` cz i've to define same function over again & using as crate is causing cyclic dependency
test:
```bash
wscat -c ws://127.0.0.1:3030/ws/health
```
in my opinion  #1256 implementation is much better than this impl, that doesn't depends upon interval & can update the frontend instantly without refreshing …
> feat: websocket for health

- CONTRIBUTING.md
fix old link to https://discord.gg/dU9EBuw7Uq (minor fix)
---
name: fixing discord link in CONTRIBUTING.md ,discord invite link is case sensitive
title: fixing discord link in CONTRIBUTING.md
---
old link
new link
> fixing discord link

- screenpipe-app-tauri/src-tauri/src/permissions.rs
- screenpipe-app-tauri/src-tauri/src/sidecar.rs
this pr adds permissions guard before starting sidecar as explained in this isse: #1346 
decided to open the issue just to explain my reasoning behind this and to keep my pr #1279 focused on ui/ux improvements
> feat(sidecar): add permissions guard before starting sidecar

- .github/workflows/release-app.yml
- screenpipe-app-tauri/src-tauri/tauri.conf.json
- screenpipe-app-tauri/src-tauri/tauri.conf.prod.json
part of work in #1279 to resolve issue #1273, opted for a separate pr to keep #1279 focused on ui/ux 
this pr adds
1. a production tauri configuration file 
2. modifies ci to use this new config file when building and releasing the tauri app
doing this keeps (dev and prod) binary name, product name and identifier separate
> feat(tauri): add prod configuration file

- screenpipe-vision/Cargo.toml
- screenpipe-vision/src/capture_screenshot_by_window.rs
- screenpipe-vision/src/core.rs
- screenpipe-vision/src/monitor.rs
- screenpipe-vision/src/utils.rs
> feat: use human friendly monitor names

- screenpipe-server/src/bin/screenpipe-server.rs
- screenpipe-server/src/lib.rs
- screenpipe-server/src/server.rs
- screenpipe-vision/src/bin/screenpipe-vision.rs
- screenpipe-vision/src/capture_screenshot_by_window.rs
- screenpipe-vision/src/monitor.rs
---
name: fix windows build 
title: "[pr] "
---
Build failed on windows 
issue screenshot
Build successful screenshot
reasons for the build faliure 
- windows thread-safety violations in monitor access across async boundaries
- deadlocks from async/mutex patterns when accessing monitor data
how i solved with my understanding
- used MonitorData struct for caching static monitor metadata
- moved monitor operations to spawn_blocking for Windows thread safety
1.cargo build --release --target x86_64-pc-windows-msvc in root folder
turn off windows firewall to avoid potential errors
Checks i made 
- Tested on windows x86_64 with 16 gb ram 
- And run dev mode sucessfully 
Attached test video 
https://github.com/user-attachments/assets/7aa9ac01-d968-4e38-8110-16c1613994af
/claim #1366
PS: happy to …
> fixes windows build

- screenpipe-audio/src/segments.rs
- screenpipe-audio/src/stt.rs
Checks speech ratio before writing audio files.
related issue: #1350
start screenpipe audio with only display device selected and don't play any audio. no files should save. Alternatively, use screenpipe audio with audio permissions disabled and ensure no audio files are written
@oliverqx
> Add speech ratio check to audio processing pipeline

- screenpipe-vision/Cargo.toml
the version selected on `Cargo.toml` is the same as nashaofu/xcap#195, but merged on my fork, so we don't have to wait xcap to be released.
I disabled the logs briefly to see if the error would keep appearing. it's not 🙌🏽
> chore: use xcap version 0.3.3 (non-released yet)

- screenpipe-app-tauri/src-tauri/src/sidecar.rs
- screenpipe-server/src/pipe_manager.rs
---
fix: #1425
fast kill for avoiding multiple instance of same pipe on different port
---
1. 
2. 
3. 
> fix: add fallback kill commands for windows

- screenpipe-app-tauri/app/page.tsx
- screenpipe-app-tauri/components/pipe-store.tsx
- screenpipe-app-tauri/src-tauri/Cargo.lock
Optimizes calls to the following endpoints
Only gets called if user token changes and the token is set, we were pinging this even if the user was not logged in
```
/api/user 
```
Only gets called if user token changes 
```
/api/plugins/user-purchase-history
```
Previous implementation checked updates even for pipes that were not installed by the user, this also checks it periodically by storing `lastCheck` in local storage
```
/api/plugins/check-update
```
> optimize API calls

- screenpipe-app-tauri/scripts/pre_build.js
@louis030195 
this will fix linux build
reason below
---
> fix potential paths for linux

- screenpipe-core/src/pipes.rs
---
watch dog shouldn't running when there is not child process
fix: #1494
---
1. 
2. 
3. 
> fix: possibly fix infinte powershell

- screenpipe-js/ai-proxy/src/handlers/chat.ts
- screenpipe-js/ai-proxy/src/handlers/models.ts
- screenpipe-js/ai-proxy/src/handlers/transcription.ts
- screenpipe-js/ai-proxy/src/handlers/voice-ws.ts
- screenpipe-js/ai-proxy/src/handlers/voice.ts
- screenpipe-js/ai-proxy/src/index.ts
- screenpipe-js/ai-proxy/src/providers/openai.ts
- screenpipe-js/ai-proxy/src/services/analytics.ts
- screenpipe-js/ai-proxy/src/services/deepgram.ts
- screenpipe-js/ai-proxy/src/types.ts
- screenpipe-js/ai-proxy/src/utils/auth.ts
- screenpipe-js/ai-proxy/src/utils/cors.ts
- screenpipe-js/ai-proxy/src/utils/rate-limiter.ts
- screenpipe-js/ai-proxy/src/utils/subscription.ts
- screenpipe-js/ai-proxy/src/utils/voice-utils.ts
Mentioned in [#1372](https://github.com/mediar-ai/screenpipe/pull/1372#issuecomment-2672075471)
Fixed structured output streaming in openai
audio -> audio
audio -> text (query)
audio -> text(transcribe)
text -> speech(rest)
> feat: support deepgram audio queries and fix streaming in openai structured outputs

- .github/workflows/release-cli.yml
using older version to support both ubuntu 22 to 24 and many older distributions
> make released cli work on ubuntu 22

- install.ps1
- screenpipe-core/src/ffmpeg.rs
```
PS C:\Users\divan> .\install.ps1
Bun is already installed and meets version requirements
```
> make sure user know that ffmpeg is being downloaded and do not re-install bun

- screenpipe-app-tauri/components/settings/disk-usage.tsx
- screenpipe-app-tauri/src-tauri/src/disk_usage.rs
fix: #1482
basically it will use `---` when the directory doesn't exist rather than crashing with `directory not found` error
> fix: disk usage

- .github/workflows/release-cli.yml
Some windows dont have onnxruntime.dll
there we will need to bundle it with our cli
> fix: screenpipe cli not working on windows 10 11

- .github/scripts/check_logs.sh
- .github/workflows/linux-integration-test.yml
* [`.github/scripts/check_logs.sh`](diffhunk://#diff-692894038c99bd1e945c34082ffa4a539a8965f838e187255757c63e09cc3f4dL7-R7): Updated the server start check to look for the server listening on `[::]:3030` instead of `127.0.0.1:3030`.
* [`.github/workflows/linux-integration-test.yml`](diffhunk://#diff-f68f8dda61a056de9750f9e069f98eee8d07a3682a8c40f6bcf8c70aeaf4463dR58-R73): Added conditions to always upload logs, captured data, and test images, ensuring these artifacts are available even if the job fails.
> fix: Linux Intergration Test

- .github/scripts/check_logs.sh
- screenpipe-app-tauri/src-tauri/src/main.rs
- screenpipe-server/src/bin/screenpipe-server.rs
fixes #1741 
fixes #1706 
fixes #1703
/claim #1084
> fix: screenpipe not working due to IPv6 port and wrong design flow

- screenpipe-audio/src/core/device.rs
---
title: "[pr] fix noise cancellation being disabled on headphones"
labels: 'bug'
assignees: '@Anmol202005'
---
This PR fixes an issue where screenpipe would sometimes disable noise cancellation on headphones. The root cause was that we were using default audio configurations instead of the device's native highest quality configuration, which could override device-specific features like noise cancellation.
Changes:
- Modified `get_cpal_device_and_config` to use device's highest quality supported configuration
- Added proper handling of `SupportedStreamConfigRange` to preserve device features
- Improved configuration selection logic to prioritize sample rate and channel count
related issue: #55
1. Connect a pair of headphones with …
> Fix: Fixed Headphones/airpods configration issue

- screenpipe-vision/src/capture_screenshot_by_window.rs
On Linux, minimized windows cannot be captured by the system, resulting in repeated error messages and cluttered log files.
---
title: "[pr] "
labels: ''
assignees: ''
---
On Linux, minimized windows cannot be captured by the system, resulting in repeated error messages and cluttered log files.
Ignore minimized windows 
1. 
2. 
3. 
if you are not the author of this PR and you see it and you think it can take more than 30 mins for maintainers to review, we will tip you between $20 and $200 …
> fix: ignore minimized windows during capture
