mediar-ai/screenpipe

- screenpipe-server/src/bin/screenpipe-server.rs
- screenpipe-server/src/bin/screenpipe-video.rs
- screenpipe-server/src/core.rs
- screenpipe-server/src/video.rs
- screenpipe-vision/Cargo.toml
- screenpipe-vision/src/core.rs
- screenpipe-vision/src/utils.rs
USE like this:
$: screenpipe --save-text-files
> Save text file flag from clie

- examples/typescript/agent-multi-turn-rag/screenpipe.ts
> chore: update screenpipe.ts

- screenpipe-vision/benches/ocr_benchmark.rs
@louis030195 I have never previously created benchmarks using Criterion. I hope this is the result we were expecting. 
Reading the mac version and how this was written + chatgpt, what I understood was:
1. We create batches and try to run them in a loop. 
2. We capture the time taken in every ocr process and cumulatively return that with the result.
> fix for ocr windows benchmark

- .github/workflows/style.yml
Will add [cargo-sort](<https://github.com/DevinR528/cargo-sort/>) check for ensuring consistent Cargo.toml formatting later, once I've found a stable configuration of [pre-commit](<https://pre-commit.com/>), to make sorting happen automatically
> GA: check for unused dependencies

- examples/typescript/pipe-security-check/README.md
- examples/typescript/pipe-security-check/main.js
added a new pipe to automatically analyze the screen data and notify the user of any potential security threat
> feat(pipe): added a new pipe security check

- examples/typescript/vercel-ai-chatbot/components/ui/codeblock.tsx
fixes type error causing broken build
> (fix): fix type error causing broken build

- screenpipe-audio/src/stt.rs
hacky hot fix, should look into why it's 32kHz here
> fix: wav audio sample rate

- screenpipe-server/src/db.rs
- screenpipe-server/src/server.rs
kinda broken
helps with reducing noise at api / search level
> min size search to reduce results noise

- examples/typescript/rag-over-your-life-in-obsidian/screenpipe.js
> chore: update screenpipe.js

- screenpipe-server/src/video.rs
fix: #319 
[demo](https://drive.google.com/file/d/1NbxUQK65aVmqEEifvIwkLY0UwY7lfgn4/view?usp=sharing)
/claim #319
> fix: video rendering issue in windows

- CONTRIBUTING.md
I noticed two typos while reading `CONTRIBUTING.md`.
> Fix typos in `CONTRIBUTING.md`

- .github/workflows/ci.yml
- screenpipe-js/main.ts
- screenpipe-js/tests/loadPipeConfig.test.ts
- **refactor: include `ParsedConfig` type**
- **test: create test for `loadPipeConfig`**
- **ci: enable deno tests on ci**
---
name: include deno tests
about: including tests specifically to `loadPipeConfig` helper, but also running up deno tests on CI
title: "[pr] ci: include `loadPipeConfig` tests and run deno tests on pipeline"
labels: 'enhancement'
assignees: 'ologbonowiwi'
---
I was looking at the code and seeing some refactors I could do, but I figured out we didn't have tests, and it'd be better to have these before refactoring anything.
pipeline should take care of it :)
I plan to write tests for the other helper functions, too, but I wrote this to see if it's on the right line.
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExam9jcmo0M2Nkb2UzYmRjaHNteWJ1d29vbnB4bXN4d3Q0M2VpbDZzciZlcD1 …
> ci: include `loadPipeConfig` tests and run deno tests on pipeline

- screenpipe-core/tests/pipes_test.rs
This fixes a failing pipes test and removes one warning.
> Fix CI (again)

- .cursorrules
add .cursorrules file to repo.
Ask who is working on screenpipe most of the time...
> add .cursorrules

- screenpipe-actions/ai-proxy/src/index.ts
- screenpipe-actions/ai-proxy/wrangler.toml
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> Updated worker

- screenpipe-app-tauri/scripts/pre_build.js
- **fix: catch error on apt-get usage**
- **feat: add target path**
> fix: handle errors thrown on endeavouros build

- screenpipe-server/src/bin/screenpipe-server.rs
---
title: "[pr] "
labels: ''
assignees: ''
---
format_cell bug fix
related issue: #535
- [- ] bug fix
> format_cell bug fix

- README-ja_JP.md
docs: add Japanese README
---
title: "[pr] "
labels: ''
assignees: ''
---
I created Japanese translated README.
> docs: ceate README-ja_JP.md

- screenpipe-app-tauri/src-tauri/tauri.windows.conf.json
@louis030195 Tell me what you think
> Fix Windows builds with Ollama

- screenpipe-audio/src/core.rs
Filter incompatible audio devices.
> filter incompatible devices from list_audio_devices

- screenpipe-audio/benches/record_and_transcribe_benchmark.rs
- screenpipe-audio/src/bin/screenpipe-audio-forever.rs
- screenpipe-audio/src/bin/screenpipe-audio.rs
- screenpipe-audio/src/core.rs
- screenpipe-audio/src/lib.rs
- screenpipe-audio/tests/core_tests.rs
- screenpipe-server/src/core.rs
This PR changes the way audio is gathered into a stream that can be subscribed to. This is the foundation of features such as realtime transcription.
related issue: #521 
1. Verify audio transcription is working as expected.
> Feat audio streaming

- screenpipe-server/benches/db_benchmarks.rs
- screenpipe-server/src/core.rs
- screenpipe-server/src/db.rs
- screenpipe-server/src/migrations/20241024181218_add_device_name_to_chunks.sql
- screenpipe-server/src/server.rs
- screenpipe-server/tests/db.rs
- screenpipe-server/tests/endpoint_test.rs
- screenpipe-server/tests/tags_test.rs
---
name: Add device_name column to Chunks Table
title: "[pr] "
labels: ''
assignees: ''
---
This fixes the bug of grabbing the correct chunk_id during insert_frame when multiple devices are writing in parallel.
1. 
2. 
3. 
> Chunks device_name column

- .github/scripts/install_dependencies.sh
- .github/workflows/release-app.yml
- screenpipe-server/Cargo.toml
/claim #318
/fix #318
This adds MKL support for Linux and Windows - since this is a CPU acceleration feature not many changes are needed.
> Add support for MKL acceleration

- .github/workflows/release-app.yml
@louis030195 One last change since you were a little too quick with the latest PR.
> Use recursive copy for MKL

- .github/workflows/ci.yml
- .github/workflows/release-app.yml
@louis030195 This should use the self-hosted runners we just set-up.
> Use self-hosted runner for Windows

- .github/workflows/release-app.yml
@louis030195 This should fix the issues
> Update actions in workflow

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/linux-integration-test.yml
- .github/workflows/perf-long-running-end-to-end.yml
- .github/workflows/publish-app.yml
- .github/workflows/release-app.yml
- .github/workflows/release-cli.yml
- .github/workflows/windows-integration-test.yml
@louis030195 Also installed git bash on the self-hosted runner.
> Update even more actions

- .github/workflows/ci.yml
- .github/workflows/linux-integration-test.yml
- .github/workflows/perf-long-running-end-to-end.yml
- .github/workflows/release-app.yml
- .github/workflows/release-cli.yml
- .github/workflows/windows-integration-test.yml
@louis030195 Somehow rustup seems to delete itself - hopefully this fixes that
> Remove warnings

- screenpipe-app-tauri/src-tauri/src/updates.rs
---
about: kill llm and screepipe process before updating.
but this issue #575 might occur again if user explicitly restarts the screenpipe backend from status ui while downloading the update, maybe i need to disable those button while update is being downloaded. 
fix: #575
---
1. 
2. 
3. 
> fix: kill llm & screenpipe sidecar berfore updating on windows

- .github/workflows/ci.yml
- .github/workflows/release-app.yml
- .github/workflows/windows-integration-test.yml
@louis030195 Also to test the new self-hosted runner.
> Use invoke-webrequest in Windows CI

- .github/workflows/windows-integration-test.yml
@louis030195 Adds a chocolatey step since our runner doesn't have it
> Add chocolatey step

- .github/workflows/release-app.yml
@louis030195 The self-hosted server should be ready now, too.
> Use self-hosted runner for release app

- screenpipe-app-tauri/lib/hooks/use-settings.tsx
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> fixed ui_monitoring toggle

- screenpipe-app-tauri/scripts/pre_build.js
@louis030195 Might fix the issue.
> Get rid of old libs if ollama is preinstalled

- screenpipe-server/src/bin/screenpipe-server.rs
---
title: "[PR] Feat: Add Screenpipe CLI to PATH "
labels: ''
assignees: ''
---
This PR adds functionality to check whether the Screenpipe CLI is in the system PATH and automatically persists it if necessary. The changes ensure that screenpipe is easily accessible after installation without requiring manual path updates.
Closes #421 
1. download screenpipe binary or build from source
2. do `screenpipe` or `screenpipe setup`
3. make sure to follow instructions in output
4. Open a new terminal session and verify that screenpipe is available in the system PATH by running `which screenpipe` or On Windows do `where screenpipe`
> feat: add screenpipe cli to PATH

- screenpipe-app-tauri/scripts/pre_build.js
@louis030195 This should reduce Azure storage expenses, also please check Telegram.
> Remove old libs from ollama for Windows

- .github/scripts/generate_changelog_md.sh
- .github/workflows/release-app.yml
- .gitignore
- content/changelogs/v0.1.98.md
- **chore: remove node_modules from git**
- **fix: exit with error if any of commit hashes are empty**
- **refactor: lock changelog generation using v0.1.98**
- **refactor: improve prompt**
- **fix: last changelog path**
- **chore: add log for last release date**
- **chore: remove quotes for commit date last release**
- **fix: include full git history**
> fix: changelog generation

- content/docs/pages/docs/getting-started.mdx
---
name: Add dependencies for linux building instruction
about: Update dependencies for the instruction of building linux from source
title: "[pr] "
labels: 'documentation'
assignees: ''
---
Update dependencies for the instruction of building linux from source
I have built successfully on my Debian machine
> Add dependencies for linux building instruction

- README-zh_CN.md
Title / 标题: docs: update Chinese documentation to sync with English version / 更新中文文档以与英文版保持同步
Updates / 更新内容：
1. Structure Adjustments / 结构调整
- Removed extra ASCII art / 删除了额外的 ASCII art
- Unified heading hierarchy / 统一了标题层级
- Maintained consistent document structure with English version / 保持与英文版相同的文档结构
2. Content Optimization / 内容优化
- Updated "How it works" section to match English style / 更新了 "工作原理" 部分，使其更简洁且符合英文版风格
- Improved slogan translation to "逐像素记录，现实永存" / 优化了标语翻译
- Enhanced product description translations for better clarity / 改进了产品描述的翻译，使其更自然且准确
3. Format Standardization / 格式统一
- Unified all heading formats / 统一了所有标题的格式
- Standardized link presentations / 统一了链接的显示方式
- Maintained consistent layout with English version / 保持了与英文版一致的排版风格
4. Additional Improvements / 其他改进
- Updated …
> update Chinese documentation to sync with English version

- .github/workflows/release-app.yml
- screenpipe-core/src/lib.rs
/claim #710 
/closes #710
This is pretty small as most of the infrastructure for the MKL support was already there.
> Reenable support for Windows MKL

- .github/workflows/release-app.yml
- screenpipe-app-tauri/src-tauri/tauri.windows.conf.json
/claim #764
/closes #764
/closes #759
I linked #764 as well because I believe the issue the user reported is directly related to this.
@louis030195 Please tell me if this is all or what other issues did you see. To address these and undraft.
> Copy necessary library for MKL support

- .github/workflows/release-app.yml
- screenpipe-app-tauri/src-tauri/tauri.windows.conf.json
@louis030195 This should fix the issue (finally) according to my tests.
/closes #759
> Fix MKL by installing necessary libraries

- screenpipe-app-tauri/src-tauri/build.rs
@louis030195 Uses unwrap in the code so it compiles.
> Unwrap code statements

- screenpipe-app-tauri/components/recording-settings.tsx
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
Double click at the data-dir select button, could modify data-dir by user typing.
> feat: change data_dir with input by double click

- screenpipe-app-tauri/src-tauri/tauri.conf.json
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> Add openrouter to the trusted connections

- .github/workflows/release-app.yml
- .github/workflows/steps/action.yml
@louis030195 Annoyingly GitHub Actions requires us to specify the shell every time we use composite actions... It might've been better to just copy code at this point
> Fix composite again

- screenpipe-app-tauri/components/timeline/timeline-dock-section.tsx
- screenpipe-app-tauri/src-tauri/src/icons.rs
---
[build](https://drive.google.com/file/d/1tMAmgf3YwvFP4oLHLCnAmKUASbaykDLO/view?usp=sharing)
fix:  #820
---
related issue:  #820
1. 
2. 
3. 
> fix: this should fix timeline crashing on windows

- content/docs/pages/docs/api-reference.mdx
- content/docs/pages/docs/getting-started.mdx
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> mild edits

- screenpipe-server/src/db.rs
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> fix: audio_search

- screenpipe-server/src/migrations/20241210205142_fix_audio_transcriptions.sql
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> fix audio_transcriptions_table

- screenpipe-app-tauri/components/screenpipe-status.tsx
---
title: "[pr] "
labels: ''
assignees: ''
/claim #903
/closes #903 
kill the screenpipe and try to open the status dialog in app
---
https://github.com/user-attachments/assets/44acf06c-578c-4015-a51e-0cbe0b542adc
1. 
2. 
3. 
> fix: clickable issue with status button on windows

- screenpipe-server/Cargo.toml
- screenpipe-server/src/bin/screenpipe-server.rs
> feat: avoid double server running

- install.sh
Previously we were using x86 ffmpeg builds on arm64 macs, this PR fixes this issue.
/closes #931
> fix ffmpeg darwin arm64

- screenpipe-audio/src/stt.rs
---
title: "[pr] "
labels: ''
assignees: ''
---
fix deepgram stt
run screenpipe using deepgram and play `screenpipe_audio/test_data/speaker_identification/6_speakers.wav`
/claim #942
> fix: deepgram stt

- .github/workflows/release-app.yml
/claim #968
/closes #968
@louis030195 Uses the ensurepip module for this.
> Fix self hosted builds

- screenpipe-app-tauri/app/timeline/page.tsx
- screenpipe-app-tauri/components/timeline/audio-transcript.tsx
---
i did some changes in timeline ui to handle connection lost.
also fixed this error, which was happening while scrolling
/closes #787
/claim #787
---
1. 
2. 
3. 
> fix(timeline-ui): connection lost and scrolling errors

- screenpipe-audio/build.rs
---
title: "[pr] "
labels: ''
assignees: ''
i'm also getting this `TimedOut` issue. now it'll time out after 300 sec
fix:  #957
---
1. 
2. 
3. 
> fix: timedout issue with screenpipe-audio

- screenpipe-app-tauri/components/pipe-store.tsx
- screenpipe-app-tauri/components/settings.tsx
- screenpipe-app-tauri/components/settings/account-section.tsx
- remove credit when buying paid pipe 
- todo way to add credit beyond existing sub (cursor like)
> add credit

- screenpipe-js/types.ts
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> Update AudioContent type

- screenpipe-server/build.rs
/claim #943
/closes #943
@louis030195 Created a new build.rs for the CLI
> Fix ONNX linking issues

- screenpipe-app-tauri/components/recording-settings.tsx
- screenpipe-app-tauri/components/ui/multi-select.tsx
https://github.com/user-attachments/assets/42243422-61a2-48b6-ada7-7980487cfce9
> multi select enhancements

- .github/workflows/release-app.yml
- screenpipe-app-tauri/src-tauri/tauri.windows.conf.json
https://github.com/Dhanus3133/screenpipe/actions/runs/12452753615/job/34762101342#step:29:1925
Fixes: #1018
/claim #1018
> fix: self hosted windows nsis build error

- screenpipe-integrations/screenpipe-mcp/README.md
- screenpipe-integrations/screenpipe-mcp/src/screenpipe_mcp/server.py
/attempt #1007
/claim #1007
claude app screeshort 
mcp inspector screenshot
currently I handled `OCR` and `audio` working on other
> fix: querry response anthropic MCP

- CONTRIBUTING.md
sometimes my Window 10 do not have winget installed
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> docs: improve windows guide in CONTRIBUTING.md

- screenpipe-app-tauri/components/pipe-config-form.tsx
- screenpipe-app-tauri/components/pipe-store.tsx
- screenpipe-app-tauri/src-tauri/Cargo.lock
- screenpipe-core/src/pipes.rs
- screenpipe-server/src/pipe_manager.rs
/claim #1124
/closes #1124
https://github.com/user-attachments/assets/f6bf936b-d490-434a-82cb-c238c0470ade
> set the port of pipes

- screenpipe-app-tauri/components/pipe-store.tsx
Forgot to uncomment this in pipe port PR, apologies.
> fix commented out line

- screenpipe-app-tauri/components/pipe-store.tsx
- screenpipe-app-tauri/src-tauri/Cargo.lock
- screenpipe-app-tauri/src-tauri/src/main.rs
- screenpipe-core/src/pipes.rs
- screenpipe-server/Cargo.toml
- screenpipe-server/src/pipe_manager.rs
Please test this before merging.
> fix killing pipes

- screenpipe-app-tauri/components/settings.tsx
- screenpipe-app-tauri/components/settings/disk-usage.tsx
- screenpipe-app-tauri/src-tauri/src/commands.rs
- screenpipe-app-tauri/src-tauri/src/disk_usage.rs
- screenpipe-app-tauri/src-tauri/src/main.rs
> feat: add disk usage in app

- pipes/memories/src/components/video.tsx
> fix: video render

- screenpipe-app-tauri/src-tauri/src/main.rs
- screenpipe-app-tauri/src-tauri/tauri.windows.conf.json
/claim #1236
/closes #1236
the `assets` directory was missing, I added it
> fix windows health icon

- screenpipe-actions/ai-proxy/src/index.ts
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> Realtime-transcription-screenpipe-cloud

- screenpipe-app-tauri/src-tauri/Cargo.toml
- screenpipe-app-tauri/src-tauri/src/icons.rs
fix: https://github.com/mediar-ai/screenpipe/pull/1203#issuecomment-2628950316
> fix: win icons

- pipes/rewind/src/app/layout.tsx
- pipes/rewind/src/app/page.tsx
- pipes/rewind/src/components/timeline/timeline-controls.tsx
fix scroll not working
related: #1203
https://github.com/user-attachments/assets/28c16451-b38f-4237-afb6-9f36fd0891e0
> fix: scroll not working

- pipes/rewind/src/app/page.tsx
- pipes/rewind/src/components/timeline/timeline-controls.tsx
fix rewind date change controls
related: #1261
https://github.com/user-attachments/assets/41802d5a-9d1e-46f6-903b-071d90444ace
> fix: rewind date change controls

- screenpipe-actions/ai-proxy/src/index.ts
- screenpipe-audio/Cargo.toml
---
title: "[pr] "
labels: ''
assignees: ''
---
Live captions now work when I deploy to my cloudflare and use my own deepgram API key.
Test with the screenpipe accounts.
related issue: #1260
/claim #1260
> fix: deepgram live transcription in screenpipe cloud

- screenpipe-js/cli/dist/index.js
- screenpipe-js/cli/src/index.ts
should fix this issue:
> https://github.com/user-attachments/assets/98b4b794-7180-4340-b773-d24218729ff6
> 
> 
> 
> 
> @oliverqx for some reason i cannot use the published CLI, works in dev mode tho
> 
> i just bumped the version to beta, `bun run build` and `bun publish`
> 
> _Originally posted by @louis030195 in https://github.com/mediar-ai/screenpipe/issues/1248#issuecomment-2640589477_
> fix(cli): add missing shebang

- screenpipe-server/src/bin/screenpipe-server.rs
- screenpipe-server/src/resource_monitor.rs
this PR shows normal logging and tokio-console when using the `debug-console` feature
> refactor: improve logging configuration and tracing setup

- screenpipe-audio/src/deepgram/realtime.rs
- screenpipe-audio/src/stt.rs
- screenpipe-core/src/devices.rs
- screenpipe-server/src/bin/screenpipe-server.rs
- screenpipe-server/src/core.rs
- screenpipe-server/src/resource_monitor.rs
The shutdown process would sometimes hang for a long time when trying to exit screenpipe.
> Fix shutdown

- screenpipe-js/cli/dist/index.js
- screenpipe-js/cli/src/commands/app/create.ts
- screenpipe-js/cli/src/commands/pipe/create.ts
fixes this:
into this:
was missing a couple try catch statements
> fix(cli): error gracefully when user exits prompt

- screenpipe-server/src/bin/screenpipe-server.rs
- screenpipe-server/src/resource_monitor.rs
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> Feat-regular-logs-and-tokio-console

- screenpipe-app-tauri/src-tauri/src/commands.rs
/claim #1316
/closes #1316
https://github.com/user-attachments/assets/e0e86bfb-be97-46cd-abd0-2af58fcf14e0
1. 
2. 
3. 
> fix: closing pipe window

- pipes/notion/src/app/api/intelligence/route.ts
- pipes/notion/src/app/api/log/route.ts
- pipes/notion/src/app/api/setup/route.ts
- pipes/notion/src/components/notion-settings.tsx
- pipes/notion/src/lib/hooks/use-pipe-settings.tsx
- pipes/obsidian/src/components/obsidian-settings.tsx
- pipes/obsidian/src/lib/hooks/use-pipe-settings.tsx
related #1340
/claim #1340
fixes the settings issue in notion / obsidian pipe
> Fix notion/obsidian pipe settings

- screenpipe-audio/Cargo.toml
- screenpipe-audio/src/core.rs
- screenpipe-audio/src/deepgram/realtime.rs
- screenpipe-audio/src/realtime.rs
- screenpipe-server/src/core.rs
based on https://github.com/mediar-ai/screenpipe/pull/1356
re-enable audio streaming
> re-enable audio streaming

- screenpipe-app-tauri/lib/hooks/use-settings.tsx
- screenpipe-app-tauri/src-tauri/src/server.rs
related to #1221 , #1342 
fixes loss of setting happening when closing or opening screenpipe app and saving screenpipe app settings
before
https://github.com/user-attachments/assets/85908570-0a21-4870-a734-d9225b146b74
after
https://github.com/user-attachments/assets/ecdc0d0d-60c2-49db-ae83-a30524306016
> fix: loss of settings

- screenpipe-app-tauri/scripts/pre_build.js
> possibly fix macOS Intel build

- screenpipe-app-tauri/src-tauri/src/permissions.rs
- screenpipe-app-tauri/src-tauri/src/sidecar.rs
1. remove camera assertion
2. remove camera from do_permissions_check, its not used
> fix: remove camera assertion before sidecar initiation

- screenpipe-app-tauri/scripts/pre_build.js
- screenpipe-app-tauri/src-tauri/Cargo.lock
- screenpipe-app-tauri/src-tauri/Info.plist
- screenpipe-app-tauri/src-tauri/entitlements.plist
- screenpipe-app-tauri/src-tauri/src/permissions.rs
- screenpipe-app-tauri/src-tauri/src/sidecar.rs
Fixes compile issues and cleans up Camera permission from plist also reverts codesign command
> fix compile issues and revert code sign

- .github/workflows/release-app.yml
@louis030195 
I already said that mkl build fails
> remove mkl from linux build

- screenpipe-app-tauri/app/page.tsx
/claim #1405
related #1405
before:
after:
> fix: overflowing of ui in app

- screenpipe-app-tauri/src-tauri/src/sidecar.rs
- screenpipe-core/src/pipes.rs
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> fix: wd on windows

- .github/workflows/release-app.yml
@louis030195 Fixes linux build
> Fix tauri args for Linux CI

- screenpipe-app-tauri/components/recording-settings.tsx
- screenpipe-app-tauri/lib/hooks/use-settings.tsx
- screenpipe-app-tauri/src-tauri/gen/schemas/linux-schema.json
- screenpipe-app-tauri/src-tauri/src/main.rs
/claim #1408
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> add autostart toggle

- screenpipe-app-tauri/components/pipe-store.tsx
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> feat: sort pipes by downloads count and creation date

- screenpipe-js/cli/dist/index.js
- screenpipe-js/cli/src/commands/pipe/publish.ts
This runs the build command in the package json ensuring project is fully compiled, also opens up options for dev to use other frameworks apart from Next.js
https://github.com/user-attachments/assets/0d062626-e572-4a3e-a831-f92b1959910b
/claim #1539
/closes #1539
> dev pipe publish prebuild

- screenpipe-app-tauri/components/pipe-store.tsx
- screenpipe-app-tauri/lib/api/store/index.ts
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> Pipe update fix

- screenpipe-js/cli/src/commands/pipe/publish.ts
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> bump pipe version if users confirms

- screenpipe-js/cli/package-lock.json
- screenpipe-js/cli/package.json
---
title: "[pr] "
labels: ''
assignees: ''
---
1. 
2. 
3. 
> cli version bumped

- screenpipe-vision/Cargo.toml
- screenpipe-vision/src/bin/screenpipe-vision.rs
- screenpipe-vision/src/capture_screenshot_by_window.rs
- screenpipe-vision/src/monitor.rs
fixes wrong focus from `0.4.0`, but with the same benefits of the latest releases.
focus PR is https://github.com/nashaofu/xcap/pull/206, but was not released yet.
> chore: bump xcap

- screenpipe-server/src/add.rs
> fix linux build

- screenpipe-app-tauri/components/pipe-store.tsx
> fix pipe store issues

- pipes/search/src/components/search-chat.tsx
fix this issue with openai and custom provider
> fix: search pipe ai not working

- screenpipe-vision/src/capture_screenshot_by_window.rs
> also capture windows having no pid

- screenpipe-app-tauri/components/pipe-store.tsx
- screenpipe-app-tauri/components/screenpipe-status.tsx
that has been removed by https://github.com/mediar-ai/screenpipe/pull/1598/
https://github.com/mediar-ai/screenpipe/pull/1598/files#r1997547844
> restore: confitmation dialog of resetting pipe

- pipes/example-pipe/components/ai-presets-dialog.tsx
- pipes/example-pipe/components/ai-presets-selector.tsx
- screenpipe-app-tauri/components/settings/ai-presets.tsx
fixes open ai models not showing up in screenpipe app settings and show all models of open ai in ai presets component
> Fix openai model not showing

- screenpipe-app-tauri/components/onboarding/api-setup.tsx
fixes issue related to ai preset of screenpipe cloud when onboarding
> fix: ai preset of screenpipe cloud not working in onboarding

- CONTRIBUTING.md
---
title: "[pr] "
labels: ''
assignees: ''
---
During installation I was prompted to upgrade my installation of xcode, which appears to be an implicit dependency for some of the build from source tools.  
N/A
> Update the build from source instructions to include xcode. 

- screenpipe-vision/benches/apple_leak_bench.rs
- screenpipe-vision/benches/ocr_benchmark.rs
- screenpipe-vision/benches/vision_benchmark.rs
Cleans up platform-specific benchmarks, fixes unused warnings, and improves error handling in vision benchmarks.
> fix: improve benchmarks and handle platform-specific code

- install.ps1
> fix: syntax error in install.ps1

- screenpipe-app-tauri/src-tauri/src/sidecar.rs
fix: #1467
@divanshu-go 
could you test it on linux, now the stop button will not kill the app, it'll only kill the backend
> fix: killing backend in linux, it shouldn't kill the app

- LICENSE.md
you forgot to update the copyright year in your licence lol
> Update copyright year in LICENSE.md

- Cargo.lock
- screenpipe-core/Cargo.toml
- screenpipe-core/examples/win_automation.rs
- screenpipe-core/src/operator/platforms/mod.rs
- screenpipe-core/src/operator/platforms/windows.rs
> feat: windows ui automation

- Cargo.lock
- screenpipe-audio/Cargo.toml
Closes #1707 
@louis030195 can we merge it ASAP
> fix compilation error due to cmake version

- screenpipe-app-tauri/scripts/pre_build.js
@louis030195 
added checks for missing APT packages and improved logging
```bash
$ bun run ./screenpipe-app-tauri/scripts/pre_build.js
cwd /home/user/screenpipe/screenpipe-app-tauri/src-tauri
the following required packages are missing:
- ffmpeg
- clang
- cmake
installing missing packages...
updating package lists...
installing packages...
(Reading database ... 245748 files and directories currently installed.)
Preparing to unpack .../clang_1%3a19.0-63_amd64.deb ...
Unpacking clang (1:19.0-63) ...
Selecting previously unselected package cmake.
Preparing to unpack .../cmake_3.31.6-1_amd64.deb ...
Unpacking cmake (3.31.6-1) ...
Selecting previously unselected package ffmpeg.
Preparing to unpack .../ffmpeg_7%3a7.1.1-1+b1_amd64.deb ...
Unpacking ffmpeg (7:7.1.1-1+b1) ...
Setting up clang …
```
> enhance linux package installation process in pre_build.js

- screenpipe-app-tauri/src-tauri/Cargo.lock
- screenpipe-app-tauri/src-tauri/Cargo.toml
- screenpipe-app-tauri/src-tauri/src/permissions.rs
update permissions handling to use core-graphics-helmer-fork for screen capture access
> refactor: use core-graphics-helmer-fork instead of scap

- .cargo/config.toml
@louis030195 
this is a more cleaner fix then having fork of several repositories.
Closes #1716 
Closes #1707
> fix cmake compile time errors

- screenpipe-app-tauri/src-tauri/src/health.rs
Before: (even when health check failed)
After
> fix: tray icon not changing on failed health check

- .github/workflows/windows-integration-test.yml
make sure .screenpipe folder is uploaded
> Update windows-integration-test.yml to upload .screenpipe folder

- CONTRIBUTING.md
- screenpipe-app-tauri/scripts/pre_build.js
@louis030195 
some users dont have Node & npm installed so they face errors
making them install node doesnt do anything as they might had installed bun using powershell script
also , some users on discord complained about structure of docs
so I fixed that too
> fix: CONTRIBUTING.md - windows part

- screenpipe-integrations/screenpipe-mcp/README.md
---
name: Add H1 and Pulse Badge to Readme
about: Adding some social proof to your readme after we had selected you as a "top-pick" in our newsletter
---
Hey Screenpipe Team,
I'm Mike from [Pulse MCP](https://www.pulsemcp.com/) and we're a community resource that's been around since the inception of the protocol. As MCP has gained widespread adoption, a lot of new servers are coming out daily and we've been thinking about how we can help the community identify the best ones.
We thought yours was a great, early server (you were quick to MCP!) and we had featured you & your server in a [prior newsletter](https://www.pulsemcp.com/posts/newsletter-remote-mcp-images-screen-recording).
We think we've built a brand that folks trust and we thought it would be helpful to start surfacing these …
> Add H1 and Pulse Badge

- screenpipe-app-tauri/components/model-download-tracker.tsx
- screenpipe-audio/src/transcription/whisper/model.rs
> fix model download ux

- screenpipe-app-tauri/components/pipe-store.tsx
- screenpipe-app-tauri/src-tauri/src/sidecar.rs
- screenpipe-server/src/bin/screenpipe-server.rs
- screenpipe-server/src/cli.rs
- screenpipe-server/src/server.rs
- screenpipe-server/tests/endpoint_test.rs
- screenpipe-server/tests/tags_test.rs
making pipe manager optional to run with cli option.
it will be helpful with rewind desktop app. since we don't need pipe manager with it
> make pipe manager optional

- CONTRIBUTING.md
Added git-ls as a dependency in CONTRIBUTING.md
> Added git-ls as a dependency in CONTRIBUTING.md
